### PR TITLE
Add generif index

### PR DESCRIPTION
**Pull request by BonfaceKilz**
Now with probeset metadata, you can query rif entries.  Example:

```
species=mouse group=BXD rif='Expression Signature' dataset='Eye M430v2 (Sep08) RMA' mean:14..15
```

### CODE REVIEW

**Comment by robwwilliams** [comment]
Great. Will try.

Rob

Robert W Williams PhD
Chair: Department of Genetics, Genomics and Informatics
UT-ORNL Governor's Chair in Computational Genomics
71 S Manassas St, Memphis TN 38163
University of Tennessee Health Science Center, TSRB 405
Cell: 901 604 4752
EMAIL: ***@***.***
Zoom: https://tennesseehipaa.zoom.us/j/9492269658
----------------

**Comment by BonfaceKilz** [comment]
@robwwilliams now we have a successful generif build in XAPIAN!  Here's the first build I deployed today: https://ci.genenetwork.org/jobs/genenetwork3-build-xapian-index/386

@jnduli has been hacking on adding the [wiki entries](https://github.com/genenetwork/genenetwork3/pull/174) while I doc and look at issues raised with Search.  Hopefully by Friday, we can demo the RIF+WIKI search.  At the very least, the RIF search should be fine in CD.

**Comment by robwwilliams** [comment]
Excellent. Out of country until July 1. Will be great to test drive asap.

Rob

Robert W Williams PhD
Chair: Department of Genetics, Genomics and Informatics
UT-ORNL Governor's Chair in Computational Genomics
71 S Manassas St, Memphis TN 38163
University of Tennessee Health Science Center, TSRB 405
Cell: 901 604 4752
EMAIL: ***@***.***
Zoom: https://tennesseehipaa.zoom.us/j/9492269658
----------------

**Comment by zsloan** [comment]
It should be pretty simple to integrate into the main search. That ended up
being a lot easier than I expected (cis/transQTL searches excepted).

**Pull request merged**
