### PR TITLE
Remove pull request template.

### PR DESCRIPTION
**Pull request by arunisaac**
People are not using the pull request template properly. Often, the fields
remain unfilled, and the placeholders are not deleted. This is cognitively
taxing for reviewers. Also, most of our changes are better described in the
commit log than in the pull request description. And, our reviews are quite
cursory and don't need a detailed pull request description for the reviewer to
act on.

We already discussed this in a stand-up, but I'm posting here again so that
everybody gets a chance to see it, and raise objections if any.

### CODE REVIEW

**Comment by BonfaceKilz** [comment]
Arun Isaac ***@***.***> anaandika:

> People are not using the pull request template properly. Often, the fields
> remain unfilled, and the placeholders are not deleted. This is cognitively
> taxing for reviewers. Also, most of our changes are better described in the
> commit log than in the pull request description. And, our reviews are quite
> cursory and don&#39;t need a detailed pull request description for the reviewer to
> act on.
>
> We already discussed this in a stand-up, but I&#39;m posting here again so that
> everybody gets a chance to see it, and raise objections if any.

I agree with this.  If no one raises any
objection, we can have this merged, sometime later
tomorrow...
-- 
Bonface M. K.
D4F09EB110177E03C28E2FE1F5BBAE1E0392253F (hkp://keys.gnupg.net)
Free Software Activist
Humble GNU Emacs User | Bearer of scheme-y parens
Curator: <https://upbookclub.com> | Twitter: @BonfaceKilz

**Comment by zsloan** [comment]
I find the first two fields useful (description + how to test, since the
latter often involves giving some specific test case), though it's true
that the template isn't needed for that and the remaining fields were
almost never filled out. Often there are many commits unrelated to the
actual functionality of the PR (like stuff cleaning up code).

**Comment by BonfaceKilz** [comment]
zsloan ***@***.***> anaandika:

> I find the first two fields useful (description + how to test, since the
> latter often involves giving some specific test case), though it's true
> that the template isn't needed for that and the remaining fields were
> almost never filled out. Often there are many commits unrelated to the
> actual functionality of the PR (like stuff cleaning up code).
>
In this case, we can get rid of the template
altogether; and should the reviewer need some
descriptive test, add that as a comment to the PR.

-- 
Bonface M. K.
D4F09EB110177E03C28E2FE1F5BBAE1E0392253F (hkp://keys.gnupg.net)
Free Software Activist
Humble GNU Emacs User | Bearer of scheme-y parens
Curator: <https://upbookclub.com> | Twitter: @BonfaceKilz

**Comment by arunisaac** [comment]
Merged, thanks!

**Pull request closed without merging**
