### PR TITLE
Heatmap generation

### PR DESCRIPTION
**Pull request by fredmanglis**
#### Description
Provide the ability for the code to generate heatmaps in a horizontal, or vertical orientation.

#### How should this be tested?
One could run the server, and then run a cURL command against it to see the output image that is generated. As an example, see 
[test_heatmaps_rework.py.zip](https://github.com/genenetwork/genenetwork3/files/7295298/test_heatmaps_rework.py.zip) to see how one would probably go about testing this.

#### Any background context you want to provide?
https://github.com/genenetwork/gn-gemtext-threads/blob/main/topics/gn1-migration-to-gn2/non-clustered-heatmaps-and-flipping.gmi

#### What are the relevant pivotal tracker stories?
https://github.com/genenetwork/gn-gemtext-threads/blob/main/topics/gn1-migration-to-gn2/non-clustered-heatmaps-and-flipping.gmi

#### Questions
N/A

### CODE REVIEW

**Comment by fredmanglis** [comment]
@zsloan @pjotrp Commit dba62ff06eaf18425db51929df85fbf01e53d49b allows the `CORS_ORIGIN` variable to be configured via the environment, so now the application can be launched with something like:

```bash
$ env FLASK_DEBUG=1 FLASK_APP="main.py" \
  SQL_URI="mysql://username:password@127.0.0.1:3306/db_webqtl" \
  TMPDIR="$(realpath .)/tmp" CORS_ORIGINS="http://test.one:*,http://test.two:2021" \
  flask run --port=8080
```

For the `CORS_ORIGINS` environment variable, provide a comma-separated list of URLs, as in the example above.


@zsloan and @BonfaceKilz would you please have a look and get this merged. It is overdue for review and merge.

**Comment by fredmanglis** [comment]
@zsloan You could set the value of `CORS_ORIGINS` environment variable to "http://gn2-zach.genenetwork.org:*" when launching GN3, to allow your GN2 to query GN3.

**Comment by fredmanglis** [comment]
@BonfaceKilz @zsloan Is there anything left to get this merged? If you can, have a look, review and get it merged, so that we can get it in front of the client(s) and start getting feedback.

**Comment by zsloan** [comment]
I'm setting CORS_ORIGINS as you mention; the specific command I'm using
when starting GN3 is: env FLASK_DEBUG=1 FLASK_APP="main.py"
CORS_ORIGINS="http://gn2-zach.genenetwork.org:*" flask run --port=8087

In the JS I get the following error (which seems like it should have been
addressed by setting CORS_ORIGINS):
Access to XMLHttpRequest at 'https://genenetwork.org/api3/heatmaps/clustered'
from origin 'http://gn2-zach.genenetwork.org' has been blocked by CORS
policy: Response to preflight request doesn't pass access control check: No
'Access-Control-Allow-Origin' header is present on the requested resource.

(The "api3" in the URL is because the NGINX configuration has
genenetwork.org/api3 point to GN3's /api; I've confirmed that GN3 is
receiving the request)

**Comment by zsloan** [comment]
Ah, I think I see the issue; I didn't realize some of your commits were in
a different branch (but not the PR). I bet it will work after I include
them; I should be able to let you know in a few minutes.

**Comment by zsloan** [comment]
Got it working now; I'll let Rob know so he can test.

**Pull request merged**
