### PR TITLE
Automated testing improvements

### PR DESCRIPTION
**Pull request by fredmanglis**
As part of the tests improvements, I have added pytest as a dependency and I'm using it to write, categorise and run the tests.

Please have a look and merge if there are no objections.

### CODE REVIEW

**Comment by arunisaac** [comment]
The commit summary of 49ec92a87d0cd49dffbc541578fc03e515864ad8 is not
descriptive. Probably make it "Test partial correlation API with no request
data" or similar.

The commit summary of 336076afe8e6ce34cc722712bdf5c9ffe9f24ac8 could be
slightly more descriptive with "Create client fixture for integration
tests".

When writing commit summaries (that is, the first line), remember that it will
often stand alone and has to make sense on its own.

In ed3a133660d23628a176425eb97c1eea0b9658bf, it is not clear what properties
are supposed to hold. Add comments making that clear.

Otherwise, LGTM! Thank you, Fred!

**Comment by fredmanglis** [comment]
@arunisaac 

> In https://github.com/genenetwork/genenetwork3/commit/ed3a133660d23628a176425eb97c1eea0b9658bf, it is not clear what properties are supposed to hold. Add comments making that clear.

Thanks for pushing back on this. In the process of trying to clarify this in the code, I improved the checks (they are badly named - still a work in progress), and in the process, I caught a subtle bug (not resolved as of this comment. see [this transitory commit](https://github.com/genenetwork/genenetwork3/pull/78/commits/09bb1c1d6ca23d02b77ad23ac0bbe2de128356c7)).

If the commit does not exist by the time you are reviewing that's fine - just means I have already improved the commit some more.

**Comment by BonfaceKilz** [comment]
Muriithi Frederick Muriuki
***@***.***> anaandika:

> As part of the tests improvements, I have added pytest as a dependency and I&#39;m using it to write, categorise and run the tests.
>

Forgive my ignorance but what improvements does
Pytest offer that Python's unittest lib offers
other than maybe extra plugins?

[...]

-- 
Bonface M. K.
D4F09EB110177E03C28E2FE1F5BBAE1E0392253F (hkp://keys.gnupg.net)
Free Software Activist
Humble GNU Emacs User | Bearer of scheme-y parens
Curator: <https://upbookclub.com> | Twitter: @BonfaceKilz

**Comment by BonfaceKilz** [comment]
> Forgive my ignorance but what improvements does
>
> Pytest offer that Python's unittest lib offers
>
> other than maybe extra plugins?

1) elimination of boilerplate (don't have to extend class to write tests)
2) Use builtin assert statement - don't have to remember `n` different assert statements
3) The pytest.mark facility to categorise tests
.
.
.
n) Don't have to write OOP code just to run tests

Muriithi Frederick Muriuki
https://fredmanglis.me.ke

Sent with ProtonMail Secure Email.

**Comment by BonfaceKilz** [comment]
4) Modular fixtures and explicit fixture-dependency declaration

Muriithi Frederick Muriuki
https://fredmanglis.me.ke

Sent with ProtonMail Secure Email.

------- Original Message -------

**Comment by fredmanglis** [comment]
@arunisaac @BonfaceKilz this is ready for your review again. I have worked on the items @arunisaac requested, and in the process ended up improving the test (and code) somewhat. Have a look and merge if you are happy with the work and commit messages.

**Comment by arunisaac** [comment]
LGTM! Please push to `main`.

**Comment by fredmanglis** [comment]
Done!

**Comment by BonfaceKilz** [comment]
Muriithi Frederick Muriuki
***@***.***> anaandika:

> @arunisaac @BonfaceKilz this is ready for your review again. I have worked on the items @arunisaac requested, and in the process ended up improving the test (and code) somewhat. Have a look and merge if you are happy with the work and commit messages.

I'll have a look at this after the stand-up.

-- 
Bonface M. K.
D4F09EB110177E03C28E2FE1F5BBAE1E0392253F (hkp://keys.gnupg.net)
Free Software Activist
Humble GNU Emacs User | Bearer of scheme-y parens
Curator: <https://upbookclub.com> | Twitter: @BonfaceKilz

**Pull request merged**
