### PR TITLE
Edit, Delete, or Add case attributes data

### PR DESCRIPTION
**Pull request by BonfaceKilz**
This PR:
- Extends editing Published Phenotypes to being able to also insert, delete, or edit case-attribute data.
- Adds regression tests for the above.

### CODE REVIEW

**Review by zsloan — APPROVED** [review]
This looks good to me.

One minor question - is the stuff with "longest header" just meant to get the additional CaseAttribute columns?

**Comment by BonfaceKilz** [comment]
zsloan ***@***.***> anaandika:

> @zsloan approved this pull request.
>
> This looks good to me.
>
> One minor question - is the stuff with "longest header" just meant to get the additional CaseAttribute columns?

This is why I avoid naming things whenever I can
;). That said, consider 2 csv files with the
following headers: "Strain Name,Value,SE,Count"
and "Strain Name,Value,SE,Count,Sex". By default,
csvdiff can't compare files with different column
headers; it will throw an error. Thus, we have to
pick the "longest" header, and on the csv file
with the shorter header, fill it with "x"s. Hope
that clarified things.


-- 
Bonface M. K.
D4F09EB110177E03C28E2FE1F5BBAE1E0392253F (hkp://keys.gnupg.net)
Free Software Activist
Humble GNU Emacs User | Bearer of scheme-y parens
Curator: <https://upbookclub.com> | Twitter: @BonfaceKilz

**Comment by zsloan** [comment]
Ah, that makes sense. Otherwise you'd run into an issue if a new column was
added in the updated CSV file. Thanks for explaining!

**Comment by BonfaceKilz** [comment]
@zsloan I'm done with this. All the tests pass. After my class I'll fix the merge conflicts, and have this merged.

**Pull request merged**
