### PR TITLE
Chore/fix failing linters

### PR DESCRIPTION
**Pull request by BonfaceKilz**
This PR:
- ignores lmdb mypy stubs
- Ignores some type hints that are difficult to trouble-shoot. @arunisaac could you have a look at: #8f9c06e and @Alexanderlacuna / @fredmanglis could you have a look at #e6aeb86 and #0930348

### CODE REVIEW

**Comment by arunisaac** [comment]
LGTM! Just one comment:

Could you use

#pylint: disable=too-many-arguments

instead of

#pylint: disable=[R0913]

It's more readable.

Thanks!

**Comment by BonfaceKilz** [comment]
Sure. I'll add that in a separate PR...

**Comment by BonfaceKilz** [comment]
So I've just directly pushed to master here: https://github.com/genenetwork/genenetwork3/commit/9afa06ec74ad07581c91445eeeae86dc30023084

**Comment by arunisaac** [comment]
> So I've just directly pushed to master here:
> https://github.com/genenetwork/genenetwork3/commit/9afa06ec74ad07581c91445eeeae86dc30023084

Thanks!

**Pull request merged**
