### PR TITLE
Partial correlations fixes

### PR DESCRIPTION
**Pull request by fredmanglis**
This adds a number of fixes to the partial correlations feature.

Please have a look and merge to main as soon as you can.

## Extra Notes

@BonfaceKilz I think you are the best person to have a look at the following, seeing as you might have been the one working on them:

- `tests/unit/db/test_traits.py:219:29`
  The command `git blame tests/unit/db/test_traits.py | grep -v "Frederick"`
  tells me you are the only other person to work on this besides me.
  There are linting errors due to arguments/parameters to a function that have
  changed.
  Please have a look and update them correctly, so that the linter will stop
  raising errors.

- `gn3/authentication.py`
  There was a linter error about "inconsistent returns". I added a
  `return None` statement at the end to kill the linter error, but might have
  inadvertently broken something where this function is used. Please review and
  replace with the appropriate fix, and remove the comments I left you.

@arunisaac I think this is mostly yours, so please have a look and fix

- Linter errors in `gn3/db/datasets.py`
  I do not know enough to change any of this safely, so I will let you handle
  these for now

- There are also some typing issues that will need fixing when you have the time

### CODE REVIEW

**Comment by arunisaac** [comment]
Thanks for the heads up, @fredmanglis ! I have fixed the linting and typing
errors I was responsible for.

pylint has a `fixme` warning that doesn't like TODO and FIXME comments, but I
think they are good practice. So, I have disabled the `fixme` warning.

In fff7954dfc7a9e843a1bca49ce0845b4f63a6342, you are replacing `NaN` with
`null` in the serialized JSON string. This is extremely dangerous. We could
easily end up replacing a valid sequence somewhere else in the string. It is
best to find and replace NaN values before the JSON tree is serialized.

Otherwise, LGTM!

**Comment by fredmanglis** [comment]
@arunisaac @BonfaceKilz I have merged this.

@BonfaceKilz Please keep in mind the issues I noted above and fix them when you are able to.

**Comment by arunisaac** [comment]
Hi Fred,

Did you see my comment on replacing NaN with null in the serialized JSON
string? It is critical.

Regards,
Arun

**Comment by fredmanglis** [comment]
@arunisaac I did. I have been trying to figure out how to actually convert it appropriately, without changing the code too much. The only problem is that it is difficult to do this correctly without introducing an extra dependency. See [this thread](https://stackoverflow.com/questions/28639953/python-json-encoder-convert-nans-to-null-instead).

It's an annoying problem.

**Comment by fredmanglis** [comment]
@arunisaac I have fixed this in commit 39779f08fd3ccf341a0855401dad1fe36119c6b4

**Comment by BonfaceKilz** [comment]
Muriithi Frederick Muriuki
***@***.***> anaandika:

> @arunisaac @BonfaceKilz I have merged this.
>
> @BonfaceKilz Please keep in mind the issues I noted above and fix them when you are able to.
>
This somehow slipped in mail.  Looking at them now.
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/genenetwork/genenetwork3/pull/67#issuecomment-1000804917
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>

-- 
Bonface M. K.
D4F09EB110177E03C28E2FE1F5BBAE1E0392253F (hkp://keys.gnupg.net)
Free Software Activist
Humble GNU Emacs User | Bearer of scheme-y parens
Curator: <https://upbookclub.com> | Twitter: @BonfaceKilz

**Pull request merged**
