### PR TITLE
delete unwanted correlation stuff

### PR DESCRIPTION
**Pull request by Alexanderlacuna**
this PR deletes unwanted files and dirs in correlation

### CODE REVIEW

**Comment by BonfaceKilz** [comment]
I'll have a go at looking at the mypy errors and pylint errors. Anyways, thanks!

**Comment by BonfaceKilz** [comment]
@Alexanderlacuna could you resolve that one merge conflict before I have this merged...

**Comment by Alexanderlacuna** [comment]
@BonfaceKilz  done!

**Comment by BonfaceKilz** [comment]
We are now green! :tada: :tada:

**Pull request merged**
