### PR TITLE
enhancements for rust tissue

### PR DESCRIPTION
**Pull request by Alexanderlacuna**

### CODE REVIEW

**Comment by BonfaceKilz** [comment]
Below lies my review:

[...]
-                "p_value": p_val
-            }
 
-            corr_results.append({trait_name: corr_data})
+            if corr_type == "sample":
+
+                corr_data = {
+                    "num_overlap": num_overlap,
+                    "corr_coefficient": corr_coeff,
+                    "p_value": p_val
+                }
+

*Question:* Shouldn't this be an if-else clause
 here?  Aren't correlations disjoint operations?

+            if corr_type == "tissue":
+                corr_data = {
+                    "tissue_corr": corr_coeff,
+                    "tissue_number": num_overlap,
+                    "tissue_p_val": p_val
+                }
+
+            corr_results[trait_name] = corr_data

See above.

-- 
(Life is like a pencil that will surely run out,
    but will leave the beautiful writing of life.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by Alexanderlacuna** [comment]
@BonfaceKilz  Nice catch they are disjoint operation but no case will both blocks be true coz I do provide a cor_type argument.

**Comment by BonfaceKilz** [comment]
Alexander Kabui ***@***.***>
aliandika:

> @BonfaceKilz  Nice catch they are disjoint operation but no case will both blocks be true coz I do provide a cor_type argument.
>

I see.  But nevertheless, you should code them as
disjoint - don't make assumptions.  It's easy on
the person who'll read it ;)

-- 
(Life is like a pencil that will surely run out,
    but will leave the beautiful writing of life.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by Alexanderlacuna** [comment]
@fredmanglis  made a few changes to the codebase

**Comment by fredmanglis** [comment]
@Alexanderlacuna @BonfaceKilz Do not push to this branch for now. I am cleaning up and rebasing changes.

**Comment by BonfaceKilz** [comment]
Muriithi Frederick Muriuki
***@***.***> aliandika:

> @Alexanderlacuna @BonfaceKilz Do not push to this branch for now. I am cleaning up and rebasing changes.
>

Thanks for the heads up.  @Alexanderlacuna when
you are done, could you give me a gentle ping,
here, on Matrix, or on e-mail to dogfood your
work?

-- 
(I Search, I Find, I Misplace, I Research)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by BonfaceKilz** [comment]
Muriithi Frederick Muriuki
***@***.***> aliandika:

> Closed #97.
>
I see it's already merged.  Ignore my previous e-mail.

-- 
(I Search, I Find, I Misplace, I Research)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Pull request closed without merging**
